var tarotcards = [
	{	"card"				:	"0 - The Fool",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"I - The Magician",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"II - The High Priestess",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"III - The Empress",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"IV - The Emperor",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"V - The Hierophant",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"VI - The Lovers",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"VII - The Chariot",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"VIII - Strength",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"IX - The Hermit",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"X - Wheel of Fortune",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"XI - Justice",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"XII - The Hanged Man",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"XIII - Death",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"XIV - Temperance",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"XV - The Devil",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"XVI - The Tower",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"XVII - The Star",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"XVIII - The Moon",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"XIX - The Sun",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"XX - Judgement",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"XXI - The World",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Ace of Wands",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Two of Wands",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Three of Wands",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Four of Wands",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Five of Wands",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Six of Wands",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Seven of Wands",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Eight of Wands",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Nine of Wands",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Ten of Wands",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Page of Wands",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Knight of Wands",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Queen of Wands",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"King of Wands",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Ace of Pentacles",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Two of Pentacles",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Three of Pentacles",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Four of Pentacles",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Five of Pentacles",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Six of Pentacles",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Seven of Pentacles",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Eight of Pentacles",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Nine of Pentacles",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Ten of Pentacles",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Page of Pentacles",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Knight of Pentacles",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Queen of Pentacles",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"King of Pentacles",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Ace of Cups",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Two of Cups",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Three of Cups",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Four of Cups",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Five of Cups",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Six of Cups",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Seven of Cups",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Eight of Cups",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Nine of Cups",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Ten of Cups",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Page of Cups",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Knight of Cups",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Queen of Cups",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"King of Cups",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Ace of Swords",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Two of Swords",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Three of Swords",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Four of Swords",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Five of Swords",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Six of Swords",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Seven of Swords",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Eight of Swords",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Nine of Swords",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Ten of Swords",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Page of Swords",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Knight of Swords",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"Queen of Swords",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	{	"card"				:	"King of Swords",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"Inverted: ",	
	},
	/*{	"card"				:	"",	
		"image"				:	"",
		"image1"			:	"",
		"image0"			:	"",	
		"description"		:	"",
		"interpretation"	:	"", 
		"interpretation1"	:	"",
		"interpretation0"	:	"",	
	},*/
];